/**
 * Made with <3 by e3ndr.
 * 
 * Licensed under MIT, do as you please.
 */
package cf.e3ndr.UltimateLib.Wrappers.Inventory;

import java.util.ArrayList;
import java.util.List;

public enum ItemType {
	IRON_NUGGET(new ItemHolder("iron_nugget", 837, "iron_nugget", 452, 0)),
	IRON_HOE(new ItemHolder("iron_hoe", 557, "iron_hoe", 292, 0)),
	FEATHER(new ItemHolder("feather", 553, "feather", 288, 0)),
	DIAMOND(new ItemHolder("diamond", 529, "diamond", 264, 0)),
	SCAFFOLDING(new ItemHolder("scaffolding", 505, "scaffolding", -165, 0)),
	STONE_SHOVEL(new ItemHolder("stone_shovel", 538, "stone_shovel", 273, 0)),
	BOOK(new ItemHolder("book", 616, "book", 340, 0)),
	STRING(new ItemHolder("string", 552, "string", 287, 0)),
	BEETROOT_SEEDS(new ItemHolder("beetroot_seeds", 821, "beetroot_seeds", 458, 0)),
	BIRCH_STAIRS(new ItemHolder("birch_stairs", 241, "birch_stairs", 135, 0)),
	AIR(new ItemHolder("air", 0, "air", -158, 0)),
	SPRUCE_FENCE_GATE(new ItemHolder("spruce_fence_gate", 217, "spruce_fence_gate", 183, 0)),
	GOLDEN_PICKAXE(new ItemHolder("golden_pickaxe", 550, "golden_pickaxe", 285, 0)),
	LIGHT_WEIGHTED_PRESSURE_PLATE(new ItemHolder("light_weighted_pressure_plate", 269, "light_weighted_pressure_plate", 147, 0)),
	SADDLE(new ItemHolder("saddle", 599, "saddle", 329, 0)),
	SMOOTH_RED_SANDSTONE_STAIRS(new ItemHolder("smooth_red_sandstone_stairs", 479, "smooth_red_sandstone_stairs", -176, 0)),
	DARK_OAK_DOOR(new ItemHolder("dark_oak_door", 512, "dark_oak_door", 431, 0)),
	MOSSY_COBBLESTONE(new ItemHolder("mossy_cobblestone", 144, "mossy_cobblestone", 48, 0)),
	MINECART(new ItemHolder("minecart", 598, "minecart", 328, 0)),
	COMPASS(new ItemHolder("compass", 621, "compass", 345, 0)),
	COOKED_CHICKEN(new ItemHolder("cooked_chicken", 680, "cooked_chicken", 366, 0)),
	SLIME_BALL(new ItemHolder("slime_ball", 617, "slime_ball", 341, 0)),
	DRIED_KELP(new ItemHolder("dried_kelp", 674, "dried_kelp", 464, 0)),
	HEART_OF_THE_SEA(new ItemHolder("heart_of_the_sea", 855, "heart_of_the_sea", 467, 0)),
	DROPPER(new ItemHolder("dropper", 280, "dropper", 125, 0)),
	GOLD_ORE(new ItemHolder("gold_ore", 29, "gold_ore", 14, 0)),
	STICKY_PISTON(new ItemHolder("sticky_piston", 74, "sticky_piston", 29, 0)),
	LOOM(new ItemHolder("loom", 858, "loom", -204, 0)),
	EGG(new ItemHolder("egg", 620, "egg", 344, 0)),
	CARTOGRAPHY_TABLE(new ItemHolder("cartography_table", 867, "cartography_table", -200, 0)),
	LINGERING_POTION(new ItemHolder("lingering_potion", 827, "lingering_potion", 441, 0)),
	COOKED_SALMON(new ItemHolder("cooked_salmon", 630, "cooked_salmon", 463, 0)),
	CRAFTING_TABLE(new ItemHolder("crafting_table", 158, "crafting_table", 58, 0)),
	ARMOR_STAND(new ItemHolder("armor_stand", 791, "armor_stand", 425, 0)),
	STONECUTTER(new ItemHolder("stonecutter", 872, "stonecutter", 245, 0)),
	HAY_BLOCK(new ItemHolder("hay_block", 299, "hay_block", 170, 0)),
	MAGMA_CREAM(new ItemHolder("magma_cream", 692, "magma_cream", 378, 0)),
	BOOKSHELF(new ItemHolder("bookshelf", 143, "bookshelf", 47, 0)),
	SHULKER_SHELL(new ItemHolder("shulker_shell", 836, "shulker_shell", 445, 0)),
	CHAINMAIL_HELMET(new ItemHolder("chainmail_helmet", 567, "chainmail_helmet", 302, 0)),
	ENCHANTED_BOOK(new ItemHolder("enchanted_book", 779, "enchanted_book", 403, 0)),
	BIRCH_PRESSURE_PLATE(new ItemHolder("birch_pressure_plate", 168, "birch_pressure_plate", -151, 0)),
	GRASS(new ItemHolder("grass", 76, "grass", 2, 0)),
	FERMENTED_SPIDER_EYE(new ItemHolder("fermented_spider_eye", 690, "fermented_spider_eye", 376, 0)),
	PURPLE_GLAZED_TERRACOTTA(new ItemHolder("purple_glazed_terracotta", 407, "purple_glazed_terracotta", 219, 0)),
	GRAVEL(new ItemHolder("gravel", 28, "gravel", 13, 0)),
	GOLDEN_CHESTPLATE(new ItemHolder("golden_chestplate", 580, "golden_chestplate", 315, 0)),
	STONE_BRICK_STAIRS(new ItemHolder("stone_brick_stairs", 223, "stone_brick_stairs", 109, 0)),
	FURNACE(new ItemHolder("furnace", 160, "furnace", 61, 0)),
	DRAGON_BREATH(new ItemHolder("dragon_breath", 823, "dragon_breath", 437, 0)),
	DIAMOND_LEGGINGS(new ItemHolder("diamond_leggings", 577, "diamond_leggings", 312, 0)),
	COOKIE(new ItemHolder("cookie", 670, "cookie", 357, 0)),
	END_CRYSTAL(new ItemHolder("end_crystal", 817, "end_crystal", 426, 0)),
	CHEST_MINECART(new ItemHolder("chest_minecart", 618, "chest_minecart", 342, 0)),
	ANDESITE_STAIRS(new ItemHolder("andesite_stairs", 488, "andesite_stairs", -171, 0)),
	PORKCHOP(new ItemHolder("porkchop", 584, "porkchop", 319, 0)),
	DARK_OAK_BUTTON(new ItemHolder("dark_oak_button", 264, "dark_oak_button", -142, 0)),
	SPLASH_POTION(new ItemHolder("splash_potion", 824, "splash_potion", 438, 0)),
	END_STONE(new ItemHolder("end_stone", 231, "end_stone", 121, 0)),
	SAND(new ItemHolder("sand", 26, "sand", 12, 0)),
	CHAIN_COMMAND_BLOCK(new ItemHolder("chain_command_block", 373, "chain_command_block", 189, 0)),
	STRIPPED_SPRUCE_LOG(new ItemHolder("stripped_spruce_log", 39, "stripped_spruce_log", -5, 0)),
	CAKE(new ItemHolder("cake", 653, "cake", 354, 0)),
	DARK_OAK_TRAPDOOR(new ItemHolder("dark_oak_trapdoor", 198, "dark_oak_trapdoor", -147, 0)),
	ANVIL(new ItemHolder("anvil", 265, "anvil", 145, 0)),
	SPRUCE_TRAPDOOR(new ItemHolder("spruce_trapdoor", 194, "spruce_trapdoor", -149, 0)),
	STONE_SWORD(new ItemHolder("stone_sword", 537, "stone_sword", 272, 0)),
	CAULDRON(new ItemHolder("cauldron", 694, "cauldron", 380, 0)),
	WRITTEN_BOOK(new ItemHolder("written_book", 758, "written_book", 387, 0)),
	EMERALD_BLOCK(new ItemHolder("emerald_block", 239, "emerald_block", 133, 0)),
	JUNGLE_STAIRS(new ItemHolder("jungle_stairs", 242, "jungle_stairs", 136, 0)),
	LECTERN(new ItemHolder("lectern", 870, "lectern", -194, 0)),
	DARK_OAK_FENCE_GATE(new ItemHolder("dark_oak_fence_gate", 221, "dark_oak_fence_gate", 186, 0)),
	SPRUCE_PRESSURE_PLATE(new ItemHolder("spruce_pressure_plate", 167, "spruce_pressure_plate", -154, 0)),
	DIAMOND_HOE(new ItemHolder("diamond_hoe", 558, "diamond_hoe", 293, 0)),
	TNT_MINECART(new ItemHolder("tnt_minecart", 782, "tnt_minecart", 407, 0)),
	LIME_GLAZED_TERRACOTTA(new ItemHolder("lime_glazed_terracotta", 402, "lime_glazed_terracotta", 225, 0)),
	NAUTILUS_SHELL(new ItemHolder("nautilus_shell", 854, "nautilus_shell", 465, 0)),
	TRIDENT(new ItemHolder("trident", 852, "trident", 455, 0)),
	BRICK(new ItemHolder("brick", 609, "brick", 336, 0)),
	SANDSTONE_STAIRS(new ItemHolder("sandstone_stairs", 235, "sandstone_stairs", 128, 0)),
	PACKED_ICE(new ItemHolder("packed_ice", 318, "packed_ice", 174, 0)),
	HEAVY_WEIGHTED_PRESSURE_PLATE(new ItemHolder("heavy_weighted_pressure_plate", 270, "heavy_weighted_pressure_plate", 148, 0)),
	DARK_OAK_STAIRS(new ItemHolder("dark_oak_stairs", 320, "dark_oak_stairs", 164, 0)),
	DRIED_KELP_BLOCK(new ItemHolder("dried_kelp_block", 613, "dried_kelp_block", -139, 0)),
	BROWN_MUSHROOM(new ItemHolder("brown_mushroom", 111, "brown_mushroom", 39, 0)),
	CHAINMAIL_LEGGINGS(new ItemHolder("chainmail_leggings", 569, "chainmail_leggings", 304, 0)),
	BAKED_POTATO(new ItemHolder("baked_potato", 764, "baked_potato", 393, 0)),
	GRANITE_STAIRS(new ItemHolder("granite_stairs", 487, "granite_stairs", -169, 0)),
	FLINT_AND_STEEL(new ItemHolder("flint_and_steel", 523, "flint_and_steel", 259, 0)),
	CAMPFIRE(new ItemHolder("campfire", 876, "campfire", 720, 0)),
	DIORITE_STAIRS(new ItemHolder("diorite_stairs", 491, "diorite_stairs", -170, 0)),
	CHAINMAIL_CHESTPLATE(new ItemHolder("chainmail_chestplate", 568, "chainmail_chestplate", 303, 0)),
	LIGHT_BLUE_GLAZED_TERRACOTTA(new ItemHolder("light_blue_glazed_terracotta", 400, "light_blue_glazed_terracotta", 223, 0)),
	GUNPOWDER(new ItemHolder("gunpowder", 554, "gunpowder", 289, 0)),
	GHAST_TEAR(new ItemHolder("ghast_tear", 684, "ghast_tear", 370, 0)),
	ENDER_CHEST(new ItemHolder("ender_chest", 237, "ender_chest", 130, 0)),
	POISONOUS_POTATO(new ItemHolder("poisonous_potato", 765, "poisonous_potato", 394, 0)),
	SHULKER_BOX(new ItemHolder("shulker_box", 380, "shulker_box", 218, 0)),
	JUNGLE_PRESSURE_PLATE(new ItemHolder("jungle_pressure_plate", 169, "jungle_pressure_plate", -153, 0)),
	SANDSTONE(new ItemHolder("sandstone", 68, "sandstone", 24, 0)),
	LEATHER_LEGGINGS(new ItemHolder("leather_leggings", 565, "leather_leggings", 300, 0)),
	RABBIT_HIDE(new ItemHolder("rabbit_hide", 790, "rabbit_hide", 415, 0)),
	BIRCH_BUTTON(new ItemHolder("birch_button", 261, "birch_button", -141, 0)),
	QUARTZ_BLOCK(new ItemHolder("quartz_block", 276, "quartz_block", 155, 0)),
	RABBIT(new ItemHolder("rabbit", 786, "rabbit", 411, 0)),
	IRON_AXE(new ItemHolder("iron_axe", 522, "iron_axe", 258, 0)),
	CHICKEN(new ItemHolder("chicken", 679, "chicken", 365, 0)),
	HOPPER(new ItemHolder("hopper", 274, "hopper", 410, 0)),
	FLOWER_POT(new ItemHolder("flower_pot", 761, "flower_pot", 390, 0)),
	CROSSBOW(new ItemHolder("crossbow", 856, "crossbow", 471, 0)),
	NETHER_BRICK_FENCE(new ItemHolder("nether_brick_fence", 227, "nether_brick_fence", 113, 0)),
	ACACIA_BUTTON(new ItemHolder("acacia_button", 263, "acacia_button", -140, 0)),
	GLASS_PANE(new ItemHolder("glass_pane", 213, "glass_pane", 102, 0)),
	DIRT(new ItemHolder("dirt", 9, "dirt", 3, 0)),
	DIAMOND_PICKAXE(new ItemHolder("diamond_pickaxe", 543, "diamond_pickaxe", 278, 0)),
	SUGAR(new ItemHolder("sugar", 652, "sugar", 353, 0)),
	DIAMOND_HELMET(new ItemHolder("diamond_helmet", 575, "diamond_helmet", 310, 0)),
	CLAY_BALL(new ItemHolder("clay_ball", 610, "clay_ball", 337, 0)),
	RED_SANDSTONE(new ItemHolder("red_sandstone", 368, "red_sandstone", 179, 0)),
	ARROW(new ItemHolder("arrow", 526, "arrow", 262, 0)),
	FISHING_ROD(new ItemHolder("fishing_rod", 622, "fishing_rod", 346, 0)),
	BUCKET(new ItemHolder("bucket", 595, "bucket", 325, 0)),
	ENCHANTING_TABLE(new ItemHolder("enchanting_table", 229, "enchanting_table", 116, 0)),
	END_PORTAL_FRAME(new ItemHolder("end_portal_frame", 230, "end_portal_frame", 120, 0)),
	APPLE(new ItemHolder("apple", 524, "apple", 260, 0)),
	POLISHED_DIORITE_STAIRS(new ItemHolder("polished_diorite_stairs", 481, "polished_diorite_stairs", -173, 0)),
	IRON_BLOCK(new ItemHolder("iron_block", 114, "iron_block", 42, 0)),
	SPONGE(new ItemHolder("sponge", 62, "sponge", 19, 0)),
	IRON_CHESTPLATE(new ItemHolder("iron_chestplate", 572, "iron_chestplate", 307, 0)),
	GOLDEN_SHOVEL(new ItemHolder("golden_shovel", 549, "golden_shovel", 284, 0)),
	KELP(new ItemHolder("kelp", 612, "kelp", 335, 0)),
	PUMPKIN_SEEDS(new ItemHolder("pumpkin_seeds", 675, "pumpkin_seeds", 361, 0)),
	QUARTZ(new ItemHolder("quartz", 781, "quartz", 406, 0)),
	GRAY_GLAZED_TERRACOTTA(new ItemHolder("gray_glazed_terracotta", 404, "gray_glazed_terracotta", 227, 0)),
	MELON(new ItemHolder("melon", 214, "melon", 360, 0)),
	GOLDEN_AXE(new ItemHolder("golden_axe", 551, "golden_axe", 286, 0)),
	CYAN_GLAZED_TERRACOTTA(new ItemHolder("cyan_glazed_terracotta", 406, "cyan_glazed_terracotta", 229, 0)),
	NETHER_WART_BLOCK(new ItemHolder("nether_wart_block", 375, "nether_wart_block", 214, 0)),
	SNOWBALL(new ItemHolder("snowball", 601, "snowball", 332, 0)),
	GLASS(new ItemHolder("glass", 64, "glass", 20, 0)),
	GLOWSTONE(new ItemHolder("glowstone", 191, "glowstone", 89, 0)),
	WHITE_GLAZED_TERRACOTTA(new ItemHolder("white_glazed_terracotta", 397, "white_glazed_terracotta", 220, 0)),
	RABBIT_STEW(new ItemHolder("rabbit_stew", 788, "rabbit_stew", 413, 0)),
	STRIPPED_OAK_LOG(new ItemHolder("stripped_oak_log", 38, "stripped_oak_log", -10, 0)),
	STONE_AXE(new ItemHolder("stone_axe", 540, "stone_axe", 275, 0)),
	SNOW(new ItemHolder("snow", 175, "snow", 80, 0)),
	IRON_ORE(new ItemHolder("iron_ore", 30, "iron_ore", 15, 0)),
	GLOWSTONE_DUST(new ItemHolder("glowstone_dust", 624, "glowstone_dust", 348, 0)),
	STRUCTURE_BLOCK(new ItemHolder("structure_block", 515, "structure_block", 252, 0)),
	BIRCH_SIGN(new ItemHolder("birch_sign", 591, "birch_sign", 473, 0)),
	BRICK_STAIRS(new ItemHolder("brick_stairs", 222, "brick_stairs", 108, 0)),
	DARK_OAK_PRESSURE_PLATE(new ItemHolder("dark_oak_pressure_plate", 171, "dark_oak_pressure_plate", -152, 0)),
	SPRUCE_BUTTON(new ItemHolder("spruce_button", 260, "spruce_button", -144, 0)),
	SMOOTH_QUARTZ_STAIRS(new ItemHolder("smooth_quartz_stairs", 486, "smooth_quartz_stairs", -185, 0)),
	WOODEN_SHOVEL(new ItemHolder("wooden_shovel", 534, "wooden_shovel", 269, 0)),
	IRON_HELMET(new ItemHolder("iron_helmet", 571, "iron_helmet", 306, 0)),
	GRINDSTONE(new ItemHolder("grindstone", 869, "grindstone", -195, 0)),
	BEETROOT_SOUP(new ItemHolder("beetroot_soup", 822, "beetroot_soup", 459, 0)),
	BLUE_GLAZED_TERRACOTTA(new ItemHolder("blue_glazed_terracotta", 408, "blue_glazed_terracotta", 231, 0)),
	GOLD_INGOT(new ItemHolder("gold_ingot", 531, "gold_ingot", 266, 0)),
	JUNGLE_FENCE_GATE(new ItemHolder("jungle_fence_gate", 219, "jungle_fence_gate", 185, 0)),
	RED_MUSHROOM_BLOCK(new ItemHolder("red_mushroom_block", 210, "red_mushroom_block", 100, 0)),
	CACTUS(new ItemHolder("cactus", 178, "cactus", 81, 0)),
	RED_MUSHROOM(new ItemHolder("red_mushroom", 112, "red_mushroom", 40, 0)),
	BARREL(new ItemHolder("barrel", 864, "barrel", -203, 0)),
	ACACIA_STAIRS(new ItemHolder("acacia_stairs", 319, "acacia_stairs", 163, 0)),
	PINK_GLAZED_TERRACOTTA(new ItemHolder("pink_glazed_terracotta", 403, "pink_glazed_terracotta", 226, 0)),
	FLETCHING_TABLE(new ItemHolder("fletching_table", 868, "fletching_table", -201, 0)),
	COOKED_RABBIT(new ItemHolder("cooked_rabbit", 787, "cooked_rabbit", 412, 0)),
	BROWN_GLAZED_TERRACOTTA(new ItemHolder("brown_glazed_terracotta", 409, "brown_glazed_terracotta", 232, 0)),
	EMERALD_ORE(new ItemHolder("emerald_ore", 236, "emerald_ore", 129, 0)),
	GOLD_NUGGET(new ItemHolder("gold_nugget", 685, "gold_nugget", 371, 0)),
	STONE_HOE(new ItemHolder("stone_hoe", 556, "stone_hoe", 291, 0)),
	REDSTONE_BLOCK(new ItemHolder("redstone_block", 272, "redstone_block", 152, 0)),
	SALMON(new ItemHolder("salmon", 626, "salmon", 460, 0)),
	DISPENSER(new ItemHolder("dispenser", 67, "dispenser", 23, 0)),
	PHANTOM_MEMBRANE(new ItemHolder("phantom_membrane", 853, "phantom_membrane", 470, 0)),
	NETHER_BRICK(new ItemHolder("nether_brick", 780, "nether_brick", 112, 0)),
	LEATHER(new ItemHolder("leather", 603, "leather", 334, 0)),
	WOODEN_SWORD(new ItemHolder("wooden_sword", 533, "wooden_sword", 268, 0)),
	GLASS_BOTTLE(new ItemHolder("glass_bottle", 688, "glass_bottle", 374, 0)),
	COAL(new ItemHolder("coal", 527, "coal", 263, 0)),
	NETHER_BRICK_STAIRS(new ItemHolder("nether_brick_stairs", 228, "nether_brick_stairs", 114, 0)),
	GOLDEN_HOE(new ItemHolder("golden_hoe", 559, "golden_hoe", 294, 0)),
	PUMPKIN(new ItemHolder("pumpkin", 187, "pumpkin", 86, 0)),
	MOSSY_STONE_BRICK_STAIRS(new ItemHolder("mossy_stone_brick_stairs", 480, "mossy_stone_brick_stairs", -175, 0)),
	GRASS_PATH(new ItemHolder("grass_path", 322, "grass_path", 198, 0)),
	OAK_STAIRS(new ItemHolder("oak_stairs", 154, "oak_stairs", 53, 0)),
	COAL_ORE(new ItemHolder("coal_ore", 31, "coal_ore", 16, 0)),
	IRON_SWORD(new ItemHolder("iron_sword", 532, "iron_sword", 267, 0)),
	TRAPPED_CHEST(new ItemHolder("trapped_chest", 268, "trapped_chest", 146, 0)),
	COMPOSTER(new ItemHolder("composter", 517, "composter", -213, 0)),
	JUNGLE_TRAPDOOR(new ItemHolder("jungle_trapdoor", 196, "jungle_trapdoor", -148, 0)),
	STONE_PICKAXE(new ItemHolder("stone_pickaxe", 539, "stone_pickaxe", 274, 0)),
	EXPERIENCE_BOTTLE(new ItemHolder("exp_bottle", 755, "experience_bottle", 384, 0)),
	DIAMOND_CHESTPLATE(new ItemHolder("diamond_chestplate", 576, "diamond_chestplate", 311, 0)),
	JUNGLE_SIGN(new ItemHolder("jungle_sign", 592, "jungle_sign", 474, 0)),
	LAPIS_ORE(new ItemHolder("lapis_ore", 65, "lapis_ore", 21, 0)),
	CHORUS_PLANT(new ItemHolder("chorus_plant", 148, "chorus_plant", 240, 0)),
	DIAMOND_BLOCK(new ItemHolder("diamond_block", 157, "diamond_block", 57, 0)),
	IRON_LEGGINGS(new ItemHolder("iron_leggings", 573, "iron_leggings", 308, 0)),
	END_ROD(new ItemHolder("end_rod", 147, "end_rod", 208, 0)),
	DIAMOND_AXE(new ItemHolder("diamond_axe", 544, "diamond_axe", 279, 0)),
	MAGENTA_GLAZED_TERRACOTTA(new ItemHolder("magenta_glazed_terracotta", 399, "magenta_glazed_terracotta", 222, 0)),
	SMOKER(new ItemHolder("smoker", 865, "smoker", -198, 0)),
	MOSSY_COBBLESTONE_STAIRS(new ItemHolder("mossy_cobblestone_stairs", 482, "mossy_cobblestone_stairs", -179, 0)),
	BAMBOO(new ItemHolder("bamboo", 614, "bamboo", -163, 0)),
	HOPPER_MINECART(new ItemHolder("hopper_minecart", 783, "hopper_minecart", 408, 0)),
	COMMAND_BLOCK_MINECART(new ItemHolder("command_block_minecart", 798, "command_block_minecart", 443, 0)),
	ACACIA_SIGN(new ItemHolder("acacia_sign", 593, "acacia_sign", 475, 0)),
	GOLDEN_SWORD(new ItemHolder("golden_sword", 548, "golden_sword", 283, 0)),
	STONE_BUTTON(new ItemHolder("stone_button", 174, "stone_button", 77, 0)),
	MYCELIUM(new ItemHolder("mycelium", 224, "mycelium", 110, 0)),
	DRAGON_EGG(new ItemHolder("dragon_egg", 233, "dragon_egg", 122, 0)),
	WOODEN_AXE(new ItemHolder("wooden_axe", 536, "wooden_axe", 271, 0)),
	COBBLESTONE(new ItemHolder("cobblestone", 12, "cobblestone", 4, 0)),
	BOW(new ItemHolder("bow", 525, "bow", 261, 0)),
	LADDER(new ItemHolder("ladder", 161, "ladder", 65, 0)),
	PUFFERFISH(new ItemHolder("pufferfish", 628, "pufferfish", 462, 0)),
	ACACIA_DOOR(new ItemHolder("acacia_door", 511, "acacia_door", 430, 0)),
	TRIPWIRE_HOOK(new ItemHolder("tripwire_hook", 238, "tripwire_hook", 131, 0)),
	STRIPPED_JUNGLE_LOG(new ItemHolder("stripped_jungle_log", 41, "stripped_jungle_log", -7, 0)),
	BEACON(new ItemHolder("beacon", 244, "beacon", 138, 0)),
	BIRCH_DOOR(new ItemHolder("birch_door", 509, "birch_door", 428, 0)),
	DIAMOND_BOOTS(new ItemHolder("diamond_boots", 578, "diamond_boots", 313, 0)),
	EMERALD(new ItemHolder("emerald", 759, "emerald", 388, 0)),
	ELYTRA(new ItemHolder("elytra", 829, "elytra", 444, 0)),
	IRON_BOOTS(new ItemHolder("iron_boots", 574, "iron_boots", 309, 0)),
	JUKEBOX(new ItemHolder("jukebox", 180, "jukebox", 84, 0)),
	BONE(new ItemHolder("bone", 651, "bone", 352, 0)),
	COOKED_PORKCHOP(new ItemHolder("cooked_porkchop", 585, "cooked_porkchop", 320, 0)),
	NETHER_WART(new ItemHolder("nether_wart", 686, "nether_wart", 372, 0)),
	POTION(new ItemHolder("potion", 687, "potion", 373, 0)),
	GOLDEN_BOOTS(new ItemHolder("golden_boots", 582, "golden_boots", 317, 0)),
	DIAMOND_SWORD(new ItemHolder("diamond_sword", 541, "diamond_sword", 276, 0)),
	MELON_SEEDS(new ItemHolder("melon_seeds", 676, "melon_seeds", 362, 0)),
	LEATHER_BOOTS(new ItemHolder("leather_boots", 566, "leather_boots", 301, 0)),
	CARVED_PUMPKIN(new ItemHolder("carved_pumpkin", 188, "carved_pumpkin", -155, 0)),
	QUARTZ_STAIRS(new ItemHolder("quartz_stairs", 278, "quartz_stairs", 156, 0)),
	CHORUS_FRUIT(new ItemHolder("chorus_fruit", 818, "chorus_fruit", 432, 0)),
	MUSHROOM_STEW(new ItemHolder("mushroom_stew", 547, "mushroom_stew", 282, 0)),
	ENDER_EYE(new ItemHolder("ender_eye", 695, "ender_eye", 381, 0)),
	POLISHED_GRANITE_STAIRS(new ItemHolder("polished_granite_stairs", 478, "polished_granite_stairs", -172, 0)),
	ACACIA_PRESSURE_PLATE(new ItemHolder("acacia_pressure_plate", 170, "acacia_pressure_plate", -150, 0)),
	COMPARATOR(new ItemHolder("comparator", 514, "comparator", 404, 0)),
	BLAZE_ROD(new ItemHolder("blaze_rod", 683, "blaze_rod", 369, 0)),
	LEATHER_CHESTPLATE(new ItemHolder("leather_chestplate", 564, "leather_chestplate", 299, 0)),
	BLAZE_POWDER(new ItemHolder("blaze_powder", 691, "blaze_powder", 377, 0)),
	CLOCK(new ItemHolder("clock", 623, "clock", 347, 0)),
	SOUL_SAND(new ItemHolder("soul_sand", 190, "soul_sand", 88, 0)),
	DARK_PRISMARINE_STAIRS(new ItemHolder("dark_prismarine_stairs", 366, "dark_prismarine_stairs", -3, 0)),
	OBSIDIAN(new ItemHolder("obsidian", 145, "obsidian", 49, 0)),
	REPEATING_COMMAND_BLOCK(new ItemHolder("repeating_command_block", 372, "repeating_command_block", 188, 0)),
	RED_NETHER_BRICK_STAIRS(new ItemHolder("red_nether_brick_stairs", 489, "red_nether_brick_stairs", -184, 0)),
	CARROT(new ItemHolder("carrot", 762, "carrot", 391, 0)),
	CHAINMAIL_BOOTS(new ItemHolder("chainmail_boots", 570, "chainmail_boots", 305, 0)),
	WHEAT(new ItemHolder("wheat", 561, "wheat", 296, 0)),
	BONE_BLOCK(new ItemHolder("bone_block", 377, "bone_block", 216, 0)),
	GOLDEN_HELMET(new ItemHolder("golden_helmet", 579, "golden_helmet", 314, 0)),
	ROTTEN_FLESH(new ItemHolder("rotten_flesh", 681, "rotten_flesh", 367, 0)),
	CONDUIT(new ItemHolder("conduit", 477, "conduit", -157, 0)),
	CLAY(new ItemHolder("clay", 179, "clay", 82, 0)),
	JUNGLE_DOOR(new ItemHolder("jungle_door", 510, "jungle_door", 429, 0)),
	SPRUCE_STAIRS(new ItemHolder("spruce_stairs", 240, "spruce_stairs", 134, 0)),
	BIRCH_FENCE_GATE(new ItemHolder("birch_fence_gate", 218, "birch_fence_gate", 184, 0)),
	GOLDEN_LEGGINGS(new ItemHolder("golden_leggings", 581, "golden_leggings", 316, 0)),
	TURTLE_HELMET(new ItemHolder("turtle_helmet", 518, "turtle_helmet", 469, 0)),
	MAP(new ItemHolder("map", 766, "map", 358, 0)),
	WOODEN_HOE(new ItemHolder("wood_hoe", 555, "wooden_hoe", 290, 0)),
	REPEATER(new ItemHolder("repeater", 513, "repeater", 356, 0)),
	REDSTONE_LAMP(new ItemHolder("redstone_lamp", 234, "redstone_lamp", 123, 0)),
	STRIPPED_DARK_OAK_LOG(new ItemHolder("stripped_dark_oak_log", 43, "stripped_dark_oak_log", -9, 0)),
	PRISMARINE(new ItemHolder("prismarine", 361, "prismarine", 168, 0)),
	PURPUR_STAIRS(new ItemHolder("purpur_stairs", 152, "purpur_stairs", 203, 0)),
	VINE(new ItemHolder("vine", 215, "vine", 106, 0)),
	BREWING_STAND(new ItemHolder("brewing_stand", 693, "brewing_stand", 379, 0)),
	POTATO(new ItemHolder("potato", 763, "potato", 392, 0)),
	COBBLESTONE_WALL(new ItemHolder("cobblestone_wall", 245, "cobblestone_wall", 139, 0)),
	GREEN_GLAZED_TERRACOTTA(new ItemHolder("green_glazed_terracotta", 410, "green_glazed_terracotta", 233, 0)),
	LEATHER_HELMET(new ItemHolder("leather_helmet", 563, "leather_helmet", 298, 0)),
	WHEAT_SEEDS(new ItemHolder("wheat_seeds", 560, "wheat_seeds", 295, 0)),
	BIRCH_TRAPDOOR(new ItemHolder("birch_trapdoor", 195, "birch_trapdoor", -146, 0)),
	DAYLIGHT_DETECTOR(new ItemHolder("daylight_detector", 271, "daylight_detector", 151, 0)),
	IRON_TRAPDOOR(new ItemHolder("iron_trapdoor", 298, "iron_trapdoor", 167, 0)),
	IRON_SHOVEL(new ItemHolder("iron_shovel", 520, "iron_shovel", 256, 0)),
	BEDROCK(new ItemHolder("bedrock", 25, "bedrock", 7, 0)),
	IRON_DOOR(new ItemHolder("iron_door", 506, "iron_door", 330, 0)),
	DETECTOR_RAIL(new ItemHolder("detector_rail", 73, "detector_rail", 28, 0)),
	JIGSAW(new ItemHolder("jigsaw", 516, "jigsaw", -211, 0)),
	BEEF(new ItemHolder("beef", 677, "beef", 363, 0)),
	SEA_PICKLE(new ItemHolder("sea_pickle", 80, "sea_pickle", -156, 0)),
	BLACK_GLAZED_TERRACOTTA(new ItemHolder("black_glazed_terracotta", 412, "black_glazed_terracotta", 235, 0)),
	REDSTONE_TORCH(new ItemHolder("redstone_torch", 173, "redstone_torch", 76, 0)),
	STONE_PRESSURE_PLATE(new ItemHolder("stone_pressure_plate", 165, "stone_pressure_plate", 70, 0)),
	SEAGRASS(new ItemHolder("seagrass", 79, "seagrass", -130, 0)),
	POLISHED_ANDESITE_STAIRS(new ItemHolder("polished_andesite_stairs", 490, "polished_andesite_stairs", -174, 0)),
	BREAD(new ItemHolder("bread", 562, "bread", 297, 0)),
	BEETROOT(new ItemHolder("beetroot", 820, "beetroot", 457, 0)),
	SMITHING_TABLE(new ItemHolder("smithing_table", 871, "smithing_table", -202, 0)),
	ORANGE_GLAZED_TERRACOTTA(new ItemHolder("orange_glazed_terracotta", 398, "orange_glazed_terracotta", 221, 0)),
	PISTON(new ItemHolder("piston", 81, "piston", 33, 0)),
	ACACIA_TRAPDOOR(new ItemHolder("acacia_trapdoor", 197, "acacia_trapdoor", -145, 0)),
	SMOOTH_STONE(new ItemHolder("smooth_stone", 140, "smooth_stone", -183, 0)),
	STONE(new ItemHolder("stone", 1, "stone", 1, 0)),
	PAINTING(new ItemHolder("painting", 586, "painting", 321, 0)),
	NAME_TAG(new ItemHolder("name_tag", 797, "name_tag", 421, 0)),
	GOLDEN_APPLE(new ItemHolder("golden_apple", 587, "golden_apple", 322, 0)),
	ACACIA_FENCE_GATE(new ItemHolder("acacia_fence_gate", 220, "acacia_fence_gate", 187, 0)),
	SWEET_BERRIES(new ItemHolder("sweet_berries", 875, "sweet_berries", 477, 0)),
	PUMPKIN_PIE(new ItemHolder("pumpkin_pie", 776, "pumpkin_pie", 400, 0)),
	STONE_STAIRS(new ItemHolder("stone_stairs", 484, "stone_stairs", 67, 0)),
	CHORUS_FLOWER(new ItemHolder("chorus_flower", 149, "chorus_flower", 200, 0)),
	ICE(new ItemHolder("ice", 176, "ice", 79, 0)),
	NETHERRACK(new ItemHolder("netherrack", 189, "netherrack", 87, 0)),
	STRIPPED_BIRCH_LOG(new ItemHolder("stripped_birch_log", 40, "stripped_birch_log", -6, 0)),
	OBSERVER(new ItemHolder("observer", 379, "observer", 251, 0)),
	ENDER_PEARL(new ItemHolder("ender_pearl", 682, "ender_pearl", 368, 0)),
	STRIPPED_ACACIA_LOG(new ItemHolder("stripped_acacia_log", 42, "stripped_acacia_log", -8, 0)),
	PAPER(new ItemHolder("paper", 615, "paper", 339, 0)),
	SHIELD(new ItemHolder("shield", 828, "shield", 513, 0)),
	PRISMARINE_CRYSTALS(new ItemHolder("prismarine_crystals", 785, "prismarine_crystals", 422, 0)),
	ACTIVATOR_RAIL(new ItemHolder("activator_rail", 279, "activator_rail", 126, 0)),
	TURTLE_EGG(new ItemHolder("turtle_egg", 445, "turtle_egg", -159, 0)),
	BLAST_FURNACE(new ItemHolder("blast_furnace", 866, "blast_furnace", -196, 0)),
	SPIDER_EYE(new ItemHolder("spider_eye", 689, "spider_eye", 375, 0)),
	BARRIER(new ItemHolder("barrier", 297, "barrier", -161, 0)),
	YELLOW_GLAZED_TERRACOTTA(new ItemHolder("yellow_glazed_terracotta", 401, "yellow_glazed_terracotta", 224, 0)),
	LANTERN(new ItemHolder("lantern", 874, "lantern", -208, 0)),
	RED_GLAZED_TERRACOTTA(new ItemHolder("red_glazed_terracotta", 411, "red_glazed_terracotta", 234, 0)),
	WOODEN_PICKAXE(new ItemHolder("wooden_pickaxe", 535, "wooden_pickaxe", 270, 0)),
	BELL(new ItemHolder("bell", 873, "bell", -206, 0)),
	PURPUR_BLOCK(new ItemHolder("purpur_block", 150, "purpur_block", 201, 0)),
	IRON_PICKAXE(new ItemHolder("iron_pickaxe", 521, "iron_pickaxe", 257, 0)),
	COOKED_BEEF(new ItemHolder("cooked_beef", 678, "cooked_beef", 364, 0)),
	LEVER(new ItemHolder("lever", 164, "lever", 69, 0)),
	PRISMARINE_STAIRS(new ItemHolder("prismarine_stairs", 364, "prismarine_stairs", -2, 0)),
	FLINT(new ItemHolder("flint", 583, "flint", 318, 0)),
	BOWL(new ItemHolder("bowl", 546, "bowl", 281, 0)),
	JUNGLE_BUTTON(new ItemHolder("jungle_button", 262, "jungle_button", -143, 0)),
	SPRUCE_DOOR(new ItemHolder("spruce_door", 508, "spruce_door", 427, 0)),
	DIAMOND_SHOVEL(new ItemHolder("diamond_shovel", 542, "diamond_shovel", 277, 0)),
	STICK(new ItemHolder("stick", 545, "stick", 280, 0)),
	GOLD_BLOCK(new ItemHolder("gold_block", 113, "gold_block", 41, 0)),
	REDSTONE_ORE(new ItemHolder("redstone_ore", 172, "redstone_ore", 73, 0)),
	COMMAND_BLOCK(new ItemHolder("command_block", 243, "command_block", 137, 0)),
	TNT(new ItemHolder("tnt", 142, "tnt", 46, 0)),
	BLUE_ICE(new ItemHolder("blue_ice", 476, "blue_ice", -11, 0)),
	TORCH(new ItemHolder("torch", 146, "torch", 50, 0)),
	FARMLAND(new ItemHolder("farmland", 159, "farmland", 60, 0)),
	RAIL(new ItemHolder("rail", 162, "rail", 66, 0)),
	RED_SANDSTONE_STAIRS(new ItemHolder("red_sandstone_stairs", 371, "red_sandstone_stairs", 180, 0)),
	IRON_BARS(new ItemHolder("iron_bars", 212, "iron_bars", 101, 0)),
	GOLDEN_CARROT(new ItemHolder("golden_carrot", 767, "golden_carrot", 396, 0)),
	BROWN_MUSHROOM_BLOCK(new ItemHolder("brown_mushroom_block", 209, "brown_mushroom_block", 99, 0)),
	LEAD(new ItemHolder("lead", 796, "lead", 420, 0)),
	SMOOTH_SANDSTONE_STAIRS(new ItemHolder("smooth_sandstone_stairs", 485, "smooth_sandstone_stairs", -177, 0)),
	PODZOL(new ItemHolder("podzol", 11, "podzol", 243, 0)),
	DIAMOND_ORE(new ItemHolder("diamond_ore", 156, "diamond_ore", 56, 0)),
	RABBIT_FOOT(new ItemHolder("rabbit_foot", 789, "rabbit_foot", 414, 0)),
	WRITABLE_BOOK(new ItemHolder("writable_book", 757, "writable_book", 386, 0)),
	SHEARS(new ItemHolder("shears", 672, "shears", 359, 0)),
	COAL_BLOCK(new ItemHolder("coal_block", 317, "coal_block", 173, 0)),
	CHEST(new ItemHolder("chest", 155, "chest", 54, 0)),
	REDSTONE(new ItemHolder("redstone", 600, "redstone", 331, 0)),
	SPRUCE_SIGN(new ItemHolder("spruce_sign", 590, "spruce_sign", 472, 0)),
	IRON_INGOT(new ItemHolder("iron_ingot", 530, "iron_ingot", 265, 0)),
	PRISMARINE_SHARD(new ItemHolder("prismarine_shard", 784, "prismarine_shard", 409, 0)),
	LAPIS_BLOCK(new ItemHolder("lapis_block", 66, "lapis_block", 22, 0));
	
	
	private ItemHolder holder;
	private ItemType(ItemHolder holder) {
		this.holder = holder;
	}
	
	/**
	 * Gets the holder.<br/>
	 * Used internally.
	 *
	 * @return the holder
	 */
	public ItemHolder getHolder() {
		return this.holder;
	}
	
	/**
	 * Gets a list of all item names.
	 * 
	 * @return a list of item names
	 */
	public static List<String> getValuesAsStringList() {
		ArrayList<String> ret = new ArrayList<>();
		
		for (ItemType it : ItemType.values()) ret.add(it.name());
		
		return ret;
	}
	
	public static ItemType getItemFromBukkit(String bukkit) {
		for (ItemType type : values()) {
			if (type.getHolder().bukkitName.equalsIgnoreCase(bukkit)) return type;
		}
		
		return AIR;
	}
	
	public static ItemType getItemFromNukkit(int nukkit, int data) {
		for (ItemType type : values()) {
			if ((type.getHolder().nukkitID == nukkit) && (type.getHolder().nukkitData == data)) return type;
		}
		
		return AIR;
	}
}